require:
  - rubocop-rspec

RSpec/BeEq: # new in 2.9.0
  Enabled: true
RSpec/BeNil: # new in 2.9.0
  Enabled: true
RSpec/ExcessiveDocstringSpacing: # new in 2.5
  Enabled: true
RSpec/IdenticalEqualityAssertion: # new in 2.4
  Enabled: true
RSpec/SubjectDeclaration: # new in 2.5
  Enabled: true
RSpec/Rails/AvoidSetupHook: # new in 2.4
  Enabled: true
RSpec/StubbedMock: # (new in 1.44)
  Enabled: true
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
RSpec/ChangeByZero: # new in 2.11
  Enabled: true
RSpec/ClassCheck: # new in 2.13
  Enabled: true
RSpec/NoExpectationExample: # new in 2.13
  Enabled: true
RSpec/SortMetadata: # new in 2.14
  Enabled: true
RSpec/VerifiedDoubleReference: # new in 2.10.0
  Enabled: true
Capybara/NegationMatcher: # new in 2.14
  Enabled: true
Capybara/SpecificActions: # new in 2.14
  Enabled: true
Capybara/SpecificFinders: # new in 2.13
  Enabled: true
Capybara/MatchStyle: # new in <<next>>
  Enabled: true
Capybara/SpecificMatcher: # new in 2.12
  Enabled: true
Capybara/ClickLinkOrButtonStyle: # new in 2.19
  Enabled: true
Capybara/RSpec/HaveSelector: # new in 2.19
  Enabled: true
Capybara/RSpec/PredicateMatcher: # new in 2.19
  Enabled: true
RSpec/Rails/HaveHttpStatus: # new in 2.12
  Enabled: true
RSpec/Rails/InferredSpecType: # new in 2.14
  Enabled: true
RSpec/NamedSubject:
  Enabled: false
RSpec/ExampleLength:
  Max: 15
  CountAsOne:
    - array
    - hash
    - heredoc
RSpec/DuplicatedMetadata: # new in 2.16
  Enabled: true
RSpec/PendingWithoutReason: # new in 2.16
  Enabled: false
RSpec/BeEmpty: # new in 2.20
  Enabled: true
RSpec/ContainExactly: # new in 2.19
  Enabled: true
RSpec/EmptyMetadata: # new in 2.24
  Enabled: true
RSpec/Eq: # new in 2.24
  Enabled: true
RSpec/IndexedLet: # new in 2.20
  Enabled: true
RSpec/MatchArray: # new in 2.19
  Enabled: true
RSpec/MetadataStyle: # new in 2.24
  Enabled: true
RSpec/ReceiveMessages: # new in 2.23
  Enabled: true
RSpec/RedundantAround: # new in 2.19
  Enabled: true
RSpec/SkipBlockInsideExample: # new in 2.19
  Enabled: true
RSpec/SpecFilePathFormat: # new in 2.24
  Enabled: true
RSpec/SpecFilePathSuffix: # new in 2.24
  Enabled: true
RSpec/Rails/NegationBeValid: # new in 2.23
  Enabled: true
RSpec/Rails/TravelAround: # new in 2.19
  Enabled: true
RSpec/Rails/MinitestAssertions: # new in 2.17
  Enabled: true

FactoryBot/SyntaxMethods: # new in 2.7
  Enabled: true
FactoryBot/ConsistentParenthesesStyle: # new in 2.14
  Enabled: true
FactoryBot/FactoryNameStyle: # new in 2.16
  Enabled: true
FactoryBot/AssociationStyle: # new in 2.23
  Enabled: true
FactoryBot/FactoryAssociationWithStrategy: # new in 2.23
  Enabled: true
FactoryBot/IdSequence: # new in <<next>>
  Enabled: true
FactoryBot/RedundantFactoryOption: # new in 2.23
  Enabled: true