require:
  - rubocop-rspec

Capybara/RedundantWithinFind: # new in 2.20
  Enabled: true
FactoryBot/ExcessiveCreateList: # new in 2.25
  Enabled: true
RSpec/EmptyOutput: # new in 2.29
  Enabled: true
RSpec/ExpectInLet: # new in 2.30
  Enabled: true
RSpec/IsExpectedSpecify: # new in 2.27
  Enabled: true
RSpec/RedundantPredicateMatcher: # new in 2.26
  Enabled: true
RSpec/RemoveConst: # new in 2.26
  Enabled: true
RSpec/RepeatedSubjectCall: # new in 2.27
  Enabled: true
RSpec/UndescriptiveLiteralsDescription: # new in 2.29
  Enabled: true
RSpec/BeEq: # new in 2.9.0
  Enabled: true
RSpec/BeNil: # new in 2.9.0
  Enabled: true
RSpec/ExcessiveDocstringSpacing: # new in 2.5
  Enabled: true
RSpec/IdenticalEqualityAssertion: # new in 2.4
  Enabled: true
RSpec/SubjectDeclaration: # new in 2.5
  Enabled: true
RSpecRails/AvoidSetupHook: # new in 2.4
  Enabled: true
RSpec/StubbedMock: # (new in 1.44)
  Enabled: true
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
RSpec/ChangeByZero: # new in 2.11
  Enabled: true
RSpec/ClassCheck: # new in 2.13
  Enabled: true
RSpec/NoExpectationExample: # new in 2.13
  Enabled: true
RSpec/SortMetadata: # new in 2.14
  Enabled: true
RSpec/VerifiedDoubleReference: # new in 2.10.0
  Enabled: true
Capybara/NegationMatcher: # new in 2.14
  Enabled: true
Capybara/SpecificActions: # new in 2.14
  Enabled: true
Capybara/SpecificFinders: # new in 2.13
  Enabled: true
Capybara/MatchStyle: # new in <<next>>
  Enabled: true
Capybara/SpecificMatcher: # new in 2.12
  Enabled: true
Capybara/ClickLinkOrButtonStyle: # new in 2.19
  Enabled: true
Capybara/RSpec/HaveSelector: # new in 2.19
  Enabled: true
Capybara/RSpec/PredicateMatcher: # new in 2.19
  Enabled: true
RSpecRails/HaveHttpStatus: # new in 2.12
  Enabled: true
RSpecRails/InferredSpecType: # new in 2.14
  Enabled: true
RSpec/NamedSubject:
  Enabled: false
RSpec/ExampleLength:
  Max: 15
  CountAsOne:
    - array
    - hash
    - heredoc
RSpec/DuplicatedMetadata: # new in 2.16
  Enabled: true
RSpec/PendingWithoutReason: # new in 2.16
  Enabled: false
RSpec/BeEmpty: # new in 2.20
  Enabled: true
RSpec/ContainExactly: # new in 2.19
  Enabled: true
RSpec/EmptyMetadata: # new in 2.24
  Enabled: true
RSpec/Eq: # new in 2.24
  Enabled: true
RSpec/IndexedLet: # new in 2.20
  Enabled: true
RSpec/MatchArray: # new in 2.19
  Enabled: true
RSpec/MetadataStyle: # new in 2.24
  Enabled: true
RSpec/ReceiveMessages: # new in 2.23
  Enabled: true
RSpec/RedundantAround: # new in 2.19
  Enabled: true
RSpec/SkipBlockInsideExample: # new in 2.19
  Enabled: true
RSpec/SpecFilePathFormat: # new in 2.24
  Enabled: true
RSpec/SpecFilePathSuffix: # new in 2.24
  Enabled: true
RSpecRails/NegationBeValid: # new in 2.23
  Enabled: true
RSpecRails/TravelAround: # new in 2.19
  Enabled: true
RSpecRails/MinitestAssertions: # new in 2.17
  Enabled: true

FactoryBot/SyntaxMethods: # new in 2.7
  Enabled: true
FactoryBot/ConsistentParenthesesStyle: # new in 2.14
  Enabled: true
FactoryBot/FactoryNameStyle: # new in 2.16
  Enabled: true
FactoryBot/AssociationStyle: # new in 2.23
  Enabled: true
FactoryBot/FactoryAssociationWithStrategy: # new in 2.23
  Enabled: true
FactoryBot/IdSequence: # new in <<next>>
  Enabled: true
FactoryBot/RedundantFactoryOption: # new in 2.23
  Enabled: true